//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using WebApplication4.Models;
    using System.Data.Entity.Infrastructure;
    
    public class WaterlillyEmployeeManagementDB1 : DbContext
    {
        public WaterlillyEmployeeManagementDB1()
            : base("name=WaterlillyEmployeeManagementDB1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    base.OnModelCreating(modelBuilder);

        //    // If needed, you can configure model here
        //    modelBuilder.Entity<EmployeeAttendance>().ToTable("EmployeeAttendances");
        //}

        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<PublicHoliday> PublicHolidays { get; set; }
        public virtual DbSet<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual DbSet<EmployeeAttendance> EmployeeAttendances { get; set; }


    }
}
